apiVersion : apps/v1
kind: Deployment
metadata:
  name: "helloworld-fadd"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "helloworld-fadd"
  template:
    metadata:
      labels:
        app: "helloworld-fadd"
      containers:
        - name: "helloworld-fadd"
          image: "nodecontainerappacr.azurecr.io/helloworld"
          ports:
          - containerPort: 8080
