apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: appname
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: appname
    spec:
      containers:
        - name: appname
          image: imagename
          ports:
          - containerPort: 8080
