apiVersion: v1
kind: Service
metadata:
    name: "helloworld-53b7"
    labels:
        app: "helloworld-53b7"
spec:
    type: LoadBalancer
    ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
    selector:
        app: "helloworld-53b7"
