apiVersion: v1
kind: Service
metadata:
    name: appname
    labels:
        app: appname
spec:
    type: LoadBalancer
    ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
    selector:
        app: appname
