name: Build and Deploy node Express app to azure
on:
  push:
    branches:
      - master

env:
  RESOURCEGROUPNAME: "devopsstarter-kubestest-rg"
  SKU: "S1 Standard"
  LOCATION: "South Central US"
  registrySku: "Basic"
  registryName: "testregistry"
  registryLocation: "South Central US"

jobs:
  build:
    name: Build and Run tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # login to azure
    - name: Login to Azure
      uses: azure/login@v1
      continue-on-error: false
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    # Deploy ARM template
    - name: Deploy ARM Template
      uses: azure/CLI@v1
      continue-on-error: false
      with:
        inlineScript: |
          az deployment group create --resource-group "${{ env.RESOURCEGROUPNAME }}" --template-file ./armTemplates/containerRegistry-template.json --parameters  registryName=="${{ env.registryName }}" registryLocation="${{ env.registryLocation }}"  registrySku="${{ env.SKU }}"
